### PR TITLE
Add cors

### PR DESCRIPTION
**Pull request by Saphyel**
As discussed here: https://github.com/api-platform/core/pull/1662

This maybe an option to add for new people

### CODE REVIEW

**Comment by soyuka** [comment]
Can't it be just a suggestion?

**Comment by Saphyel** [comment]
@soyuka can be... happy to change it

**Comment by soyuka** [comment]
IMO it should be in "suggest" we don't want the package by default.

**Comment by Saphyel** [comment]
@soyuka done!

**Review by soyuka — APPROVED** [review]

**Review by sroze — APPROVED** [review]

**Comment by reducio** [comment]
`nelmio/cors-bundle` should be included in the api-pack, absolutely!

**Pull request merged**
